spring:
  datasource:
    url: jdbc:h2:mem:tests
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: off
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#  sql:
#    init:
#      schema-locations: classpath:h2/schema.sql
#      data-locations: classpath:h2/data.sql
#      mode: always

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
